# Generated by Django 5.0.6 on 2024-07-08 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 8 digits', regex='^\\d{8}$')])),
                ('region', models.CharField(choices=[('BE', 'Beirut'), ('SD', 'Saida'), ('TR', 'Tripoly'), ('TY', 'Tyr'), ('AA', 'Aalay')], max_length=2)),
            ],
        ),
    ]
