# Generated by Django 5.0.6 on 2024-07-08 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 8 digits', regex='^\\d{8}$')]),
        ),
    ]
