# Generated by Django 4.2.7 on 2024-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField()),
                ('location', models.CharField(choices=[('BE', 'Beirut'), ('SL', 'South Lebanon'), ('ML', 'Mount Lebanon'), ('NL', 'North Lebanon'), ('AK', 'Akkar'), ('BK', 'Bekaa'), ('BH', 'Baalbak-Hermel')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'Female')], default=('M', 'MALE'), max_length=1),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'Female')], default=('M', 'MALE'), max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('BE', 'Beirut'), ('SL', 'South Lebanon'), ('ML', 'Mount Lebanon'), ('NL', 'North Lebanon'), ('AK', 'Akkar'), ('BK', 'Bekaa'), ('BH', 'Baalbak-Hermel')], max_length=2),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='bio',
            field=models.TextField(max_length=300),
        ),
    ]
