# Generated by Django 4.2.7 on 2024-07-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0005_alter_company_location_alter_customer_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
