# Generated by Django 4.2.7 on 2024-07-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0007_remove_freelancer_gender_freelancer_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('creative_services', 'Creative Services'), ('technology_services', 'Technology Services'), ('marketing_and_sales', 'Marketing and Sales'), ('health_and_wellness', 'Health and Wellness'), ('business_services', 'Business Services'), ('education_and_training', 'Education and Training'), ('home_and_maintenance', 'Home and Maintenance'), ('events_and_entertainment', 'Events and Entertainment'), ('fashion_and_beauty', 'Fashion and Beauty'), ('travel_and_tourism', 'Travel and Tourism')], default=('creative_services', 'Creative Services'), max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
