# Generated by Django 4.2.7 on 2024-07-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0008_remove_company_location_company_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(choices=[('BE', 'Beirut'), ('SL', 'South Lebanon'), ('ML', 'Mount Lebanon'), ('NL', 'North Lebanon'), ('AK', 'Akkar'), ('BK', 'Bekaa'), ('BH', 'Baalbak-Hermel'), ('JN', 'Jounieh')], default=('BE', 'Beirut'), max_length=2),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='location',
            field=models.CharField(choices=[('BE', 'Beirut'), ('SL', 'South Lebanon'), ('ML', 'Mount Lebanon'), ('NL', 'North Lebanon'), ('AK', 'Akkar'), ('BK', 'Bekaa'), ('BH', 'Baalbak-Hermel'), ('JN', 'Jounieh')], default=('BE', 'Beirut'), max_length=2),
        ),
    ]
