# Generated by Django 4.2.7 on 2024-07-20 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0009_company_location_freelancer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid URL. Example: https://www.example.com', regex='^(https?:\\/\\/)?(www\\.)?[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}(\\/[a-zA-Z0-9#]+\\/?)*$')]),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'Female')], default=('M', 'MALE'), max_length=1),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid URL. Example: https://www.example.com', regex='^(https?:\\/\\/)?(www\\.)?[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}(\\/[a-zA-Z0-9#]+\\/?)*$')]),
        ),
    ]
