# Generated by Django 4.2.7 on 2024-07-20 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0010_company_website_freelancer_gender_freelancer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid URL including a TLD. Example: https://www.example.com', regex='^(https?:\\/\\/)?(www\\.)?[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}(\\/[a-zA-Z0-9#]+\\/?)*$')]),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid URL including a TLD. Example: https://www.example.com', regex='^(https?:\\/\\/)?(www\\.)?[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}(\\/[a-zA-Z0-9#]+\\/?)*$')]),
        ),
    ]
