from django.core.validators import RegexValidator

class USERS():
    GENDER = [
        ('M', 'MALE'),
        ('F', 'Female')
    ]
    CITIES_CHOICES = [
            ('BE', 'Beirut'),
            ('SL', 'South Lebanon'),
            ('ML', 'Mount Lebanon'),
            ('NL', 'North Lebanon'),
            ('AK', 'Akkar'),
            ('BK', 'Bekaa'),
            ('BH', 'Baalbak-Hermel'),
            ('JN', 'Jounieh')
        ]

class SERVICES():
    SERVICE_CATEGORIES = [
    ('creative_services', 'Creative Services'),
    ('technology_services', 'Technology Services'),
    ('marketing_and_sales', 'Marketing and Sales'),
    ('health_and_wellness', 'Health and Wellness'),
    ('business_services', 'Business Services'),
    ('education_and_training', 'Education and Training'),
    ('home_and_maintenance', 'Home and Maintenance'),
    ('events_and_entertainment', 'Events and Entertainment'),
    ('fashion_and_beauty', 'Fashion and Beauty'),
    ('travel_and_tourism', 'Travel and Tourism'),
    ]

    PROFESSIONS = {
        'creative_services': [
            ('graphic_designer', 'Graphic Designer'),
            ('illustrator', 'Illustrator'),
            ('photographer', 'Photographer'),
            ('videographer', 'Videographer'),
            ('copywriter', 'Copywriter'),
            ('editor', 'Editor'),
            ('animator', 'Animator'),
            ('art_director', 'Art Director'),
            ('fashion_designer', 'Fashion Designer'),
            ('interior_designer', 'Interior Designer'),
            ('web_designer', 'Web Designer'),
            ('music_producer', 'Music Producer'),
            ('voice_over_artist', 'Voice-over Artist'),
        ],
        'technology_services': [
            ('software_developer', 'Software Developer'),
            ('web_developer', 'Web Developer'),
            ('mobile_app_developer', 'Mobile App Developer'),
            ('it_support_specialist', 'IT Support Specialist'),
            ('network_engineer', 'Network Engineer'),
            ('data_scientist', 'Data Scientist'),
            ('cybersecurity_analyst', 'Cybersecurity Analyst'),
            ('database_administrator', 'Database Administrator'),
            ('system_administrator', 'System Administrator'),
            ('ux_ui_designer', 'UX/UI Designer'),
            ('cloud_architect', 'Cloud Architect'),
            ('devops_engineer', 'DevOps Engineer'),
            ('game_developer', 'Game Developer'),
        ],
        'marketing_and_sales': [
            ('digital_marketer', 'Digital Marketer'),
            ('social_media_manager', 'Social Media Manager'),
            ('seo_specialist', 'SEO Specialist'),
            ('content_marketer', 'Content Marketer'),
            ('email_marketer', 'Email Marketer'),
            ('ppc_specialist', 'PPC Specialist'),
            ('sales_consultant', 'Sales Consultant'),
            ('market_research_analyst', 'Market Research Analyst'),
            ('brand_strategist', 'Brand Strategist'),
            ('public_relations_specialist', 'Public Relations Specialist'),
            ('affiliate_marketer', 'Affiliate Marketer'),
            ('advertising_specialist', 'Advertising Specialist'),
            ('event_marketer', 'Event Marketer'),
        ],
        'health_and_wellness': [
            ('personal_trainer', 'Personal Trainer'),
            ('nutritionist', 'Nutritionist'),
            ('physical_therapist', 'Physical Therapist'),
            ('mental_health_counselor', 'Mental Health Counselor'),
            ('massage_therapist', 'Massage Therapist'),
            ('yoga_instructor', 'Yoga Instructor'),
            ('chiropractor', 'Chiropractor'),
            ('occupational_therapist', 'Occupational Therapist'),
            ('wellness_coach', 'Wellness Coach'),
            ('acupuncturist', 'Acupuncturist'),
            ('dietitian', 'Dietitian'),
            ('health_coach', 'Health Coach'),
            ('aromatherapist', 'Aromatherapist'),
        ],
        'business_services': [
            ('accountant', 'Accountant'),
            ('bookkeeper', 'Bookkeeper'),
            ('legal_consultant', 'Legal Consultant'),
            ('business_coach', 'Business Coach'),
            ('virtual_assistant', 'Virtual Assistant'),
            ('hr_consultant', 'HR Consultant'),
            ('financial_advisor', 'Financial Advisor'),
            ('management_consultant', 'Management Consultant'),
            ('tax_consultant', 'Tax Consultant'),
            ('project_manager', 'Project Manager'),
            ('business_analyst', 'Business Analyst'),
            ('office_manager', 'Office Manager'),
            ('marketing_consultant', 'Marketing Consultant'),
        ],
        'education_and_training': [
            ('tutor', 'Tutor'),
            ('online_course_creator', 'Online Course Creator'),
            ('corporate_trainer', 'Corporate Trainer'),
            ('language_instructor', 'Language Instructor'),
            ('educational_consultant', 'Educational Consultant'),
            ('college_counselor', 'College Counselor'),
            ('music_teacher', 'Music Teacher'),
            ('art_instructor', 'Art Instructor'),
            ('driving_instructor', 'Driving Instructor'),
            ('test_prep_coach', 'Test Prep Coach'),
            ('career_coach', 'Career Coach'),
            ('professional_development_trainer', 'Professional Development Trainer'),
            ('life_coach', 'Life Coach'),
        ],
        'home_and_maintenance': [
            ('house_cleaner', 'House Cleaner'),
            ('landscaper', 'Landscaper'),
            ('plumber', 'Plumber'),
            ('electrician', 'Electrician'),
            ('handyman', 'Handyman'),
            ('painter', 'Painter'),
            ('carpenter', 'Carpenter'),
            ('hvac_technician', 'HVAC Technician'),
            ('pest_control_specialist', 'Pest Control Specialist'),
            ('roof_repair_specialist', 'Roof Repair Specialist'),
            ('appliance_repair_technician', 'Appliance Repair Technician'),
            ('pool_cleaner', 'Pool Cleaner'),
            ('locksmith', 'Locksmith'),
        ],
        'events_and_entertainment': [
            ('event_planner', 'Event Planner'),
            ('wedding_planner', 'Wedding Planner'),
            ('dj', 'DJ'),
            ('caterer', 'Caterer'),
            ('party_rental_provider', 'Party Rental Provider'),
            ('magician', 'Magician'),
            ('comedian', 'Comedian'),
            ('balloon_artist', 'Balloon Artist'),
            ('florist', 'Florist'),
            ('photographer_videographer', 'Photographer/Videographer'),
            ('event_decorator', 'Event Decorator'),
            ('live_band_musician', 'Live Band/Musician'),
            ('stage_performer', 'Stage Performer'),
        ],
        'fashion_and_beauty': [
            ('hairstylist', 'Hairstylist'),
            ('makeup_artist', 'Makeup Artist'),
            ('fashion_designer', 'Fashion Designer'),
            ('personal_shopper', 'Personal Shopper'),
            ('nail_technician', 'Nail Technician'),
            ('barber', 'Barber'),
            ('esthetician', 'Esthetician'),
            ('wardrobe_consultant', 'Wardrobe Consultant'),
            ('tattoo_artist', 'Tattoo Artist'),
            ('skin_care_specialist', 'Skin Care Specialist'),
            ('beauty_consultant', 'Beauty Consultant'),
            ('bridal_stylist', 'Bridal Stylist'),
            ('hair_colorist', 'Hair Colorist'),
        ],
        'travel_and_tourism': [
            ('tour_guide', 'Tour Guide'),
            ('travel_agent', 'Travel Agent'),
            ('transportation_service_provider', 'Transportation Service Provider'),
            ('hotel_manager', 'Hotel Manager'),
            ('travel_blogger', 'Travel Blogger'),
            ('flight_attendant', 'Flight Attendant'),
            ('wedding_planner', 'Wedding Planner'),
            ('travel_consultant', 'Travel Consultant'),
        ],
    }

class VALIDATORS():

    website_validator = RegexValidator(
    regex=r'^(https?:\/\/)?(www\.)?[a-zA-Z0-9-]+\.[a-zA-Z]{2,}(\/[a-zA-Z0-9#]+\/?)*$',
    message='Enter a valid URL including a TLD. Example: https://www.example.com'
)